#
# This is a default ProFTPD configuration file for NC1 
#

#======================= Global Settings =======================

ServerName			"LG-NAS FTP server"
ServerType			standalone
DefaultServer			on
ServerIdent			off
UseReverseDNS			off
IdentLookups			off
Port				21
PassivePorts			55536 55663

AllowOverwrite			on
AllowRetrieveRestart		on
AllowStoreRestart		on

Umask				0
MaxInstances			30

User				nobody
Group				nogroup

DefaultRoot 			/mnt/disk/
UseEncoding			utf8 cp949

ListOptions			-a
ShowSymlinks			off

TimesGMT			off
SetEnv				TZ :/etc/localtime

TransferLog			/var/log/proftpd/xferlog
<Limit SITE_CHMOD>
  DenyAll
</Limit>

<IfModule mod_tls.c>
  TLSEngine on
  TLSLog TLSLog  /var/log/proftpd/ftps.log
  TLSProtocol TLSv1

  # Are clients required to use FTP over TLS when talking to this server?
  TLSRequired off

  # Server's certificate
  TLSRSACertificateFile /etc/ssl/certs/signed-req.pem
  TLSRSACertificateKeyFile /etc/ssl/certs/req.key

  # CA the server trusts
  TLSCACertificateFile /etc/ssl/certs/ca.crt

  # Authenticate clients that want to use FTP over TLS?
  TLSVerifyClient off
</IfModule>

<IfModule mod_facts.c>
  FactsAdvertise      off
</IfModule>


#======================= Share Definitions =======================

### BEGIN VOLUME INFO
### END VOLUME INFO
