# logrotate configuration file for NC1

size 		100k
rotate 		2
create		0644 root root

include 	/etc/logrotate.d

# system-specific logs may be configured here

/var/log/syslog /var/log/cron.log /var/log/daemon.log /var/log/kern.log /var/log/lpr.log {
	notifempty
	missingok
	postrotate
	sharedscripts
	postrotate
		/usr/bin/killall -HUP syslogd
	endscript
}

/var/log/nas.log {
	notifempty
	missingok
	postrotate
	sharedscripts
	postrotate
		/usr/bin/killall -HUP syslogd
	endscript
}

/var/log/nas.log.old {
	notifempty
	missingok
}

/var/log/samba.log {
	notifempty
	missingok
	postrotate
	sharedscripts
	postrotate
		/usr/bin/killall -HUP syslogd
	endscript
}

