#!/bin/bash

#===============================================================================
# nas-disk 
#===============================================================================

LIBDIR=$PREFIX/usr/lib/nas/
. $LIBDIR/storage.sh

case "$1" in
  "hddsetup")
    [ $# -lt 5 ] && usage "$1 TYPE FORMAT SIZE1 SIZE2"
    hddsetup $2 $3 $4 $5
    ;;
  "check_md1")
    [ $# -lt 1 ] && usage "$1 "
    check_md1 $2
    ;;
  "grow_raid")
    [ $# -lt 1 ] && usage "$1 "
    grow_raid 
    ;;
  "get_disk_info")
    [ $# -lt 1 ] && usage "$1 "
    SYS_GetDiskInfoAndSaveScsi 
    ;;
  "clean_mount_dir")
    clean_mount_dir
    ;;
  "usb_mount")
    shift
    usb_mount $@
    ;;
  "odd_mount")
    [ -z "$2" ] && usage "$1 DEVICE"
    odd_mount $2
    ;;
  "odd_umount")
    [ -z "$2" ] && usage "$1 DEVICE"
    odd_umount $2
    ;;
  "usb_backup")
    usb_backup
    ;;
  "odd_backup")
    odd_backup $2 $3
    ;;
  "usb_copy")
    usb_copy $2 $3
    ;;
  "odd_burn")    
    odd_burn $2
    ;;
  "usb_cancel")
    usb_cancel
    ;;
  "odd_cancel")
    odd_cancel
    ;;
  "usb_sync")
    usb_sync
    ;;
  "get_control_num")
    shift
    get_device_name $1 full
    ;;
  "gen_usb_info")
    shift
    gen_usb_backup_info $@
    ;;
  "get_usb_list")
    shift
    get_usb_backup_list $@
    ;;
  "get_device_name")
    shift
    get_device_name $@
    ;;
  "test")
    check_auto_backup $2
    ;;
  "get")
    [ $# -lt 2 ] && usage "$1 PROPERTY"
    disk_get $2 $3 
    ;;
  "hddscan")
    [ $# -ne 2 ] && usage "$1 TARGET"
    hddscan $2
    ;;
  *)
    usage "{get}" 
    ;;
esac

exit $?
