#
# Default configuration file for the Samba suite for NC1
#

#======================= Global Settings =======================

[global]

  # language
  display charset = UTF-8
  unix charset = UTF-8
  dos charset = CP949

  workgroup = WORKGROUP 
  server string = LG-NAS server
  dns proxy = no
  use sendfile = yes
  panic action = /usr/share/samba/panic-action %d
  security = user
  unix password sync = yes
  passwd program = /usr/bin/passwd %u
  passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .

  hide dot files = Yes
  veto files = /.AppleDesktop/Network Trash Folder/TheVolumeSettingsFolder/.AppleDouble/.AppleDB/.burn/Temporary Items/.svn/:2eDS_Store/
  delete veto files = Yes
  invalid users = root
  deadtime = 15

  invalid users = root
  guest account = nobody
  map to guest = Bad User
  unix extensions = no
  mangled names = yes
  mangle prefix = 6

  # log  
  syslog = 0
  syslog only = Yes

  # printer 
  disable spoolss = Yes
  show add printer wizard = No
  load printers = No
  use client driver = Yes
  printing = lprng 

  # tuning
  socket options = TCP_NODELAY TCP_QUICKACK SO_RCVBUF=65535 SO_SNDBUF=65535 
  
### BEGIN ACTIVE DIRECTORY CONF
  realm = NC1AD.LOCAL 
  winbind enum users = Yes
  winbind enum groups = Yes
  idmap uid = 600-20000
  idmap gid = 600-20000
### END ACTIVE DIRECTORY CONF

#======================= Share Definitions =======================
