# Button Configuration #
12:fan	:nas-micom INFO_FAN
13:ip	:nas-micom INFO_IP
14:usage :nas-micom INFO_USAGE
15:version:nas-micom INFO_FWVER
16:micom:nas-micom INFO_MICOM
17:date :nas-micom INFO_TIME
18:temp :nas-micom INFO_TEMP
26:usb inc :nas-storage usb_backup &
27:odd data :nas-storage odd_backup data &
28:odd image :nas-storage odd_backup image &
29:fstab :nas-micom INFO_FSTAB
32:onetouch:nas-storage usb_backup onetouch &
35:usb sync:nas-storage usb_sync
36:usb cancel:nas-storage usb_cancel
37:odd cancel:nas-storage odd_cancel
39:hiber exec:nas-system start_hibernation
45:poweroff:nas-system shutdown 
46:ip	:nas-micom INFO_IP
47:reboot:/hib_reboot.sh
