# Network configuration file

# IP setting refer /etc/network/interfaces 

# Domain information
domain_type 	= workgroup
workgroup 	= WORKGROUP
domain 		= NONE
domain_user 	= NONE
domain_pass 	= NONE

# iscsi-scst CHAP configuration
iscsi_chap = off
iscsi_inuser = inAdmin
iscsi_inpw = in0123456789
iscsi_outuser = outAdmin
iscsi_outpw = out123456789
# iscsi-scst CHAP default information
iscsi_definuser = inAdmin
iscsi_definpw = in0123456789
iscsi_defoutuser = outAdmin
iscsi_defoutpw = out123456789

