#
# NC1 system configuration file
#

# Language
codepage = CP949

# NTP settings
ntp = off
ntpserver = none
default_ntpserver = pool.ntp.org
ntp_update = 1w

# Schedule Backup
schedule = on
schedule_method = Incremental
schedule_cycle = 1w

# Hibernation
hibernation = off
hibernation_time = 30

# UPS setting
ups = off
ups_shutdown_time = 0
ups_poweroff = on

# Scheduled power on/off
schedule_power = off
schedule_power_Stime = 21:10
schedule_power_Etime = 4:30

# Email Notification
email_alert = off
email_to = none
email_subject = NAS Status Report
email_term = Daily 
email_hdd_report = off

smtp_server = none
smtp_auth = off
smtp_user = none
smtp_pass = none
smtp_ssl = off

