#! /bin/sh 
### BEGIN INIT INFO
# Provides:          dlnad
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description: DLNA daemon 
# Description:       DLNA daemon 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="DLNA daemon"
NAME=dlnad
#DAEMON=dms_sync
#DAEMON_ARGS=conf
DAEMON_DIR=/usr/sbin/DLNA
DAEMON_PATH=/usr/sbin/DLNA/dms_sync
DAEMON_ARG=/usr/sbin/DLNA/conf

PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

MAX_USER_WATCHES=100000
MAX_USER_WATCHES_PATH=/proc/sys/fs/inotify/max_user_watches


# Exit if the package is not installed
[ -x "$DAEMON_PATH" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	export DU_LOG_LEVEL=0
	if [ -f $MAX_USER_WATCHES_PATH -a -w $MAX_USER_WATCHES_PATH ]; then
    		echo $MAX_USER_WATCHES > $MAX_USER_WATCHES_PATH
	fi

	echo "Starting DLNA"	
	#"$DAEMON_PATH/$DAEMON" "$DAEMON_PATH/$DAEMON_ARGS" "$DAEMON_PATH"

	start-stop-daemon --start \
		--background --exec $DAEMON_PATH -- $DAEMON_ARG $DAEMON_DIR 
	return $?
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	
        echo "Shutting down DLNA"
	#killall $DAEMON_PATH
	start-stop-daemon --stop \
		--exec $DAEMON_PATH
	return $?
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
