#! /bin/sh 
### BEGIN INIT INFO
# Provides:          nas-init
# Required-Start:    
# Required-Stop:     
# Default-Start:     S 
# Default-Stop:      0 1 6
# Short-Description: NAS initialization 
# Description:       NAS initialization
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="iSCSI target"

. /lib/init/vars.sh
. /lib/lsb/init-functions
. /usr/lib/nas/service.sh
export DEBUG=off

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	[ -e /dev/sr0 ] || return 2
	nas-service set_iscsi iqn $(hostname)
	/etc/init.d/scst start
	/etc/init.d/iscsi-scst start
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred

	/etc/init.d/iscsi-scst stop
	/etc/init.d/scst stop
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_action_msg "Starting $DESC" 
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_daemon_msg "$DESC start"; log_end_msg 0;;
		2) [ "$VERBOSE" != no ] && log_daemon_msg "$DESC start"; log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_action_msg "Stopping $DESC" 
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_daemon_msg "$DESC stop"; log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_daemon_msg "$DESC stop"; log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
