# Forward all requests for /transmission to transmission-daemon
ProxyPass /transmission/rpc http://127.0.0.1:9092/transmission/rpc
ProxyPassReverse /transmission/rpc http://127.0.0.1:9092/transmission/rpc
ProxyPass /transmission/upload http://127.0.0.1:9092/transmission/upload
ProxyPassReverse /transmission/upload http://127.0.0.1:9092/transmission/upload
