#! /bin/sh 
### BEGIN INIT INFO
# Provides:          nas-init
# Required-Start:    
# Required-Stop:     
# Default-Start:     S 
# Default-Stop:      0 1 6
# Short-Description: NAS initialization 
# Description:       NAS initialization
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="NAS pre-initialization"

. /usr/lib/nas/common.sh

log_start() {
	# create log file
	LOG_FILE=/var/log/nas.log
	if [ -e "$LOG_FILE" ]; then
		cat $LOG_FILE >> $LOG_FILE.old 
		rm $LOG_FILE
	fi
	touch $LOG_FILE
	echo "=================================================================" >> $LOG_FILE
	echo " DSS-NC1 LOG" >> $LOG_FILE
	echo "=================================================================" >> $LOG_FILE
	echo "HOSTNAME:" $(cat /etc/hostname) >> $LOG_FILE
	echo "VERSION:" $(nas-firmware get version) >> $LOG_FILE
	echo "KERNEL:" $(sysctl -n kernel.revision) >> $LOG_FILE
	echo "TIME:" $(date) >> $LOG_FILE
	echo "INTERFACE:" >> $LOG_FILE
		cat /etc/network/interfaces >> $LOG_FILE
	echo "=================================================================" >> $LOG_FILE
	
	# check kernel version
	REQUIRED=$(awk '/kernel.revision/ {print $3}' /etc/nas/firmware.conf)
	LOADED=$(sysctl -n kernel.revision) 
	echo " * Checking kernel revision $REQUIRED = $LOADED"
}

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started

	# set system clock from hwclock (UTC)
	hwclock -s -u

	mkdir -p /var/run/nas/
	touch /var/run/nas/booting

	# remove mount infomation and remove directory
	cat /dev/null > /etc/mtab
        cat /dev/null > /var/run/nas-usb.list
        cat /dev/null > /var/run/nas-usb.device

	# remove usb samba share info
	nas-share del_samba_usb_all

	# nas-storage clean_mount_dir
	rm -rf $USB_MOUNT_DIR/*
	rm -rf $ESATA_MOUNT_DIR/*
	rm -rf $CDROM_MOUNT_DIR/*
	rm -rf $SDMMC_MOUNT_DIR/*

	# regen web server conf
	nas-service gen_web_conf

	log_start &
}

case "$1" in
  start)
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start}" >&2
	exit 3
	;;
esac

:
