#!/bin/sh

### BEGIN INIT INFO
# Provides:          samba
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Should-Start:      slapd
# Should-Stop:       slapd
# Short-Description: start Samba daemons (nmbd and smbd)
### END INIT INFO


# Defaults
RUN_MODE="daemons"
USE_DOMAIN=yes

# Reads config file (will override defaults above)
[ -r /etc/default/samba ] && . /etc/default/samba

PIDDIR=/var/run/samba
NMBDPID=$PIDDIR/nmbd.pid
SMBDPID=$PIDDIR/smbd.pid

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemons are there
test -x /usr/sbin/nmbd -a -x /usr/sbin/smbd || exit 0

. /lib/lsb/init-functions

# Domain Information 
if [ "$USE_DOMAIN" = "yes" ]; then
  if [ "$1" != "reload" ]; then
    DOMAIN_TYPE=$(nas-network get domain_type)
    DOMAIN=$(nas-network get domain)
    DOMAIN_USER=$(nas-network get domain_user)
    DOMAIN_PASS=$(nas-network get domain_pass)
  fi
fi

case "$1" in
	start)
		log_daemon_msg "Starting Samba daemons"
		# Make sure we have our PIDDIR, even if it's on a tmpfs
		install -o root -g root -m 755 -d $PIDDIR

		NMBD_DISABLED=`testparm -s --parameter-name='disable netbios' 2>/dev/null`
		if [ "$NMBD_DISABLED" != 'Yes' ]; then
			log_progress_msg "nmbd"
			if ! start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/nmbd -- -D
			then
				log_end_msg 1
				exit 1
			fi
		fi

		if [ "$RUN_MODE" != "inetd" ]; then
			log_progress_msg "smbd"
			if ! start-stop-daemon --start --quiet --oknodo --nicelevel -17 --exec /usr/sbin/smbd -- -D; then
				log_end_msg 1
				exit 1
			fi
		fi
## AD Start
		if [ "$DOMAIN_TYPE" = "domain" ]; then

			ntpdate $DOMAIN
			echo $DOMAIN_PASS | kinit "$DOMAIN_USER"
			if [ "$?" != "0" ]; then
				log_end_msg 1
				exit 1
			fi

			net ads join -U "$DOMAIN_USER"%"$DOMAIN_PASS"
			if [ "$?" = "0" ]; then
				winbindd -D
			else
				log_end_msg 1
				exit 1
			fi

		fi
## AD END

		log_end_msg 0
		;;
	stop)
		log_daemon_msg "Stopping Samba daemons"
		log_progress_msg "nmbd"

		start-stop-daemon --stop --quiet --pidfile $NMBDPID
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $NMBDPID ] && ! ps h `cat $NMBDPID` > /dev/null
		then
			# Stale PID file (nmbd was succesfully stopped),
			# remove it (should be removed by nmbd itself IMHO.)
			rm -f $NMBDPID
		fi

		if [ "$RUN_MODE" != "inetd" ]; then
			log_progress_msg "smbd"
			start-stop-daemon --stop --quiet --pidfile $SMBDPID
			# Wait a little and remove stale PID file
			sleep 1
			if [ -f $SMBDPID ] && ! ps h `cat $SMBDPID` > /dev/null
			then
				# Stale PID file (nmbd was succesfully stopped),
				# remove it (should be removed by smbd itself IMHO.)
				rm -f $SMBDPID
			fi
		fi

		pkill winbindd
		log_end_msg 0

		;;
	reload)
		log_daemon_msg "Reloading /etc/samba/smb.conf" "smbd only"

		#start-stop-daemon --stop --signal HUP --pidfile $SMBDPID
		if [ -e "$SMBDPID" ]; then
			smbcontrol smbd reload-config
		fi

		log_end_msg 0
		;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		exit $?
		;;
	*)
		echo "Usage: /etc/init.d/samba {start|stop|reload|restart|force-reload}"
		exit 1
		;;
esac

exit 0
