#
# DDNS configuration file
#

update_period_sec 60
forced_update_period 5
username nctest
password nctest
dyndns_system default@lgnas.com
#dyndns_system custom@dyndns.org
alias nctest.lgnas.com
dyndns_server_name ns.lgnas.com:80
dyndns_server_url /nic/update?
#background
