
[general]
web_root = /usr/share/mt-daapd/admin-root
port = 3689
admin_pw = admin
db_type = sqlite3
db_parms = /usr/var/cache/mt-daapd
mp3_dir = /tmp
servername = iTunes Server on LG-NAS
runas = nobody
extensions = .mp3,.m4a,.m4p,.m4v,.aif,.aiff

#ssc_codectypes = ogg,flac,mp4a,mpeg,alac,alac
#ssc_prog = /usr/bin/mt-daapd-ssc.sh
#logfile = /var/log/mt-daapd.log

rescan_interval = 3600
#always_scan = 1
scan_type = 0


[plugins]
plugin_dir = /usr/lib/mt-daapd/plugins

[scanning]
process_playlists = 1
process_itunes = 1
process_m3u = 1
mp3_tag_codepage = CP949
