02	-	S		/etc/init.d/mountkernfs.sh
02	-	S		/etc/init.d/nas-preinit
02	-	S		/etc/init.d/hostname.sh
03	-	S		/etc/init.d/module-init-tools
03	-	S		/etc/init.d/udev
10	-	S		/etc/init.d/sysklogd
11	-	S		/etc/init.d/klogd
12	-	S		/etc/init.d/dbus
18	-	S		/etc/init.d/ifupdown-clean
20	-	S		/etc/init.d/lighttpd
20	-	S		/etc/init.d/ifplugd
22	-	S		/etc/init.d/mtab.sh
35	-	S		/etc/init.d/mountall.sh
35	-	S		/etc/init.d/telnetd
36	-	S		/etc/init.d/udev-mtab
39	-	S		/etc/init.d/ifupdown
40	-	S		/etc/init.d/networking
43	0,6	S		/etc/init.d/portmap
45	-	S		/etc/init.d/buttond
50	-	S		/etc/init.d/nas-init
65	-	S		/etc/init.d/avahi-daemon
89	-	S		/etc/init.d/crond
# THE LAST LINE IS NEVER READ
