#  /etc/syslog.conf	Configuration file for syslogd.

*.*;local6.none			-/var/log/syslog
cron.*				-/var/log/cron.log
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
lpr.*				-/var/log/lpr.log

# NAS specific log

local1.*			/var/log/nas.log
local1.*			/dev/console
local6.*			-/var/log/samba.log

