### BEGIN PRINTER INFO
[nas-printer]
  comment = Network Printer for Windows
  path = /var/spool/samba
  print command = /usr/bin/lpr -r -Pnas-printer %s
  force user = root
  printer name = nas-printer
  public = Yes
  printable = Yes
  browseable = Yes
  available = Yes
### END PRINTER INFO
